apiVersion: apps/v1 
kind: Deployment 
metadata:   
  name: dvwa-deployment 
spec:  
  replicas: 1  
  selector:   
    matchLabels:   
      app: dvwa 
  template:  
    metadata:    
      labels:    
        app: dvwa 
    spec:     
      containers:    
      - name: dvwa    
        image: cambarts/arm-dvwa   
        ports:      
        - containerPort: 80
